apiVersion: skaffold/v2beta26
kind: Config
metadata:
  name: me--
build:
  artifacts:
    - image: 560914023379.dkr.ecr.us-east-2.amazonaws.com/marketplace-engine
      docker:
        dockerfile: Dockerfile
deploy:
  kubectl:
    defaultNamespace: myriad-flow
    manifests:
      - k8s/gateway-deploy.yml
      - k8s/gateway-ingress.yml
      - k8s/gateway-service.yml
