apiVersion: skaffold/v2beta26
kind: Config
metadata:
  name: me--
build:
  artifacts:
    - image: public.ecr.aws/s8n8b4h8/myriad-flow-gateway
      docker:
        dockerfile: Dockerfile
deploy:
  kubectl:
    defaultNamespace: myriad-flow
    manifests:
      - k8s/gateway-deploy.yml
      - k8s/gateway-ingress.yml
      - k8s/gateway-service.yml
