apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-app
spec:
  selector:
    matchLabels:
      app: creatify-marketplace
      type: postgres-database
  template:
    metadata:
      labels:
        app: creatify-marketplace
        type: postgres-database
    spec:
      containers:
        - name: postgres-app
          image: postgres
          resources:
            limits:
              memory: "128Mi"
              cpu: "100m"
          ports:
            - containerPort: 5432
          env:
            - name: "POSTGRES_PASSWORD"
              value: revotic
            - name: "POSTGRES_USER"
              value: revotic
            - name: "POSTGRES_DB"
              value: marketplace
