name: "Test"

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    container: golang:buster
    env:
      DB_HOST: postgres
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      DB_NAME: postgres
      DB_PORT: 5432
      NODE_URL:  ${{ secrets.NODE_URL }}
      MNEMONIC:  ${{ secrets.MNEMONIC }}
      CREATIFY_CONTRACT_ADDRESS: ${{ secrets.CREATIFY_CONTRACT_ADDRESS }}

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v2
      - name: Install gotestsum
        run: go get -u gotest.tools/gotestsum
      - name: Build
        run: go build -v ./...
      - name: Test
        run: LOAD_CONFIG_FILE=false gotestsum
